development:
  adapter: postgresql
  encoding: unicode
  database: myapp_dev
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: bparanj
  password: